# Generated by Django 4.2.16 on 2025-01-13 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_type', models.CharField(choices=[('A', 'Shift A (08:00 - 16:00)'), ('B', 'Shift B (16:00 - 00:00)'), ('C', 'Shift C (00:00 - 08:00)')], max_length=1)),
                ('start_time', models.TimeField(editable=False)),
                ('end_time', models.TimeField(editable=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
    ]
