# Generated by Django 4.2.16 on 2025-01-14 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='present',
            name='status',
            field=models.CharField(choices=[('P', 'Present'), ('A', 'Absent'), ('L', 'Late'), ('E', 'Excused')], default='A', max_length=1),
        ),
    ]
