# Generated by Django 4.2.16 on 2025-02-05 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='shift_type',
            field=models.CharField(choices=[('A', 'Shift A (06:00 - 14:00)'), ('B', 'Shift B (14:00 - 22:00)'), ('C', 'Shift C (22:00 - 06:00)')], max_length=1),
        ),
    ]
