# Generated by Django 4.2.16 on 2025-02-06 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_alter_shift_shift_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='shift_type',
            field=models.CharField(choices=[('A', 'Shift A (03:00 - 09:00)'), ('B', 'Shift B (09:00 - 15:00)'), ('C', 'Shift C (15:00 - 21:00)'), ('D', 'Shift D (21:00 - 03:00)')], max_length=1),
        ),
    ]
