# Generated by Django 4.2.16 on 2025-02-11 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_alter_shift_shift_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='shift_type',
            field=models.CharField(choices=[('A', 'Shift A (04:00 - 12:00)'), ('B', 'Shift B (12:00 - 20:00)'), ('C', 'Shift C (20:00 - 04:00)')], max_length=1),
        ),
    ]
