# Generated by Django 4.2.16 on 2025-02-14 08:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0010_alter_shift_shift_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='shift_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
