# Generated by Django 4.2.16 on 2025-02-18 07:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0011_shift_shift_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='shift_date',
        ),
        migrations.AddField(
            model_name='shift',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
