# Generated by Django 4.2.16 on 2025-02-18 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0012_remove_shift_shift_date_shift_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
