# Generated by Django 4.2.16 on 2025-02-19 02:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0014_event_shiftcalendar_delete_events_remove_shift_date_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shiftcalendar',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='shiftcalendar',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='shiftcalendar',
            name='user',
        ),
    ]
