# Generated by Django 4.2.16 on 2025-02-24 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0015_alter_shiftcalendar_unique_together_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
